=== rolfwessels/databaseversioncontrol/src/DVCSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by rolf_wessels (Private) -->
<!--W3C Schema generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="AT_ProfileTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="sqlServer"/>
      <xs:enumeration value="mySql"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AT_Date">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="AT_String">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="At_Bool">
		<xs:restriction base="xs:string">
			<xs:enumeration value="True"/>
			<xs:enumeration value="False"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AT_int">
		<xs:restriction base="xs:int"/>
	</xs:simpleType>
	<xs:simpleType name="AT_decimal">
		<xs:restriction base="xs:decimal"/>
	</xs:simpleType>
	<xs:element name="property">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="AT_String"/>
					<xs:attribute name="name" type="AT_String" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="updates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sqlRunner" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="trackingByTable">
		<xs:complexType>
			<xs:attribute name="tableName" type="AT_String" use="required"/>
			<xs:attribute name="autoCreate" type="At_Bool" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="sqlRunner">
		<xs:complexType id="sqlrunnerid">
			<xs:sequence>
				<xs:element ref="command"/>
				<xs:element ref="rollback" minOccurs="0"/>
				<xs:element ref="testData" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="index" type="AT_decimal" use="required"/>
			<xs:attribute name="description" type="AT_String" use="required"/>
			<xs:attribute name="createBy" type="AT_String" use="required"/>
			<xs:attribute name="createDate" type="AT_Date" use="required"/>
      <xs:attribute name="skipTransaction" type="At_Bool" use="optional"/>
      
    </xs:complexType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="file"/>
					<xs:attribute name="files"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="rollback">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sql"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="testData">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="sql"/>
				<xs:element ref="csv"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="repositoryProfile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="trackingByTable"/>
				<xs:element ref="properties" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="type" type="AT_ProfileTypeEnum" use="required"/>
			<xs:attribute name="repositoryID" type="AT_String" use="required"/>
			<xs:attribute name="databaseName" type="AT_String" use="required"/>
			<xs:attribute name="commandTimeout" type="AT_int" use="optional"/>
			<xs:attribute name="connectionString" type="AT_String" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="repository">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="properties" minOccurs="0"/>
				<xs:element ref="initialRunner"/>
				<xs:element ref="updates"/>
			</xs:sequence>
			<xs:attribute name="id" type="AT_String" use="required"/>
		</xs:complexType>
		<xs:unique name="Unique">
			<xs:selector xpath="updates/sqlRunner"/>
			<xs:field xpath="@index"/>
		</xs:unique>
	</xs:element>
	<xs:element name="repositories">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="repository"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="profiles">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="profile"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="profile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="repositoryProfile"/>
			</xs:sequence>
			<xs:attribute name="id" type="AT_String" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="initialRunner">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sqlRunner"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="databaseVersion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="profiles"/>
				<xs:element ref="repositories"/>
			</xs:sequence>
			<xs:attribute name="defaultProfile" type="AT_String" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="command">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="sql"/>
				<xs:element ref="csv"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="csv">
		<xs:complexType>
			<xs:attribute name="datafile" use="required"/>
			<xs:attribute name="table" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rolfwessels/databaseversioncontrol/src/DVCSchema.sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by rolf_wessels (Private) -->
<databaseVersion defaultProfile="Default" xsi:noNamespaceSchemaLocation="DVCSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<profiles>
		<profile id="Default">
			<repositoryProfile type="sqlServer" connectionString="data source=Localhost;Integrated Security=True;" databaseName="DvcTest" repositoryID="MainDatabase">
				<trackingByTable tableName="DVC_Tracking" autoCreate="True"/>
			</repositoryProfile>
		</profile>
		<profile id="ProfileDeveloper">
			<repositoryProfile type="sqlServer" commandTimeout="30" connectionString="data source=Localhost;Integrated Security=True;" databaseName="DvcTest" repositoryID="MainDatabase">
				<trackingByTable tableName="DVC_Tracking" autoCreate="True"/>
				<properties>
					<property name="Pre.InitialRunner.Rollback">
                EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = '${dp.DatabaseName};'
                ALTER DATABASE [${dp.DatabaseName}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
              </property>
				</properties>
			</repositoryProfile>
		</profile>
	</profiles>
	<repositories>
		<repository id="MainDatabase">
			<properties>
				<property name="Pre.InitialRunner.Rollback" value=""/>
			</properties>
			<initialRunner>
				<sqlRunner index="1" createDate="2010-04-16" description="Initialize script" createBy="Rolf Wessels">
					<command>
						<sql>
						${Pre.InitialRunner.Rollback}
						create database ${dp.DatabaseName}</sql>
					</command>
					<rollback>
						<sql>
            drop database ${dp.DatabaseName}</sql>
					</rollback>
				</sqlRunner>
			</initialRunner>
			<updates>
				<sqlRunner index="2" description="Create Products" createDate="2010-05-25" createBy="Rolf">
					<command>
						<sql>
              CREATE TABLE [Product] (
              [SellableProductID] bigint NOT NULL,
              [Title] varchar(200) NOT NULL,
              [ArtistName] varchar(200) NOT NULL,
              [ImageName] varchar(200) NOT NULL,
              [Price] Decimal(8,2) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Product] PRIMARY KEY ([SellableProductID])
              )
              ON [PRIMARY]
            </sql>
					</command>
					<rollback>
						<sql>drop table Product</sql>
					</rollback>
				</sqlRunner>
				<sqlRunner index="3" description="Additional tables required" createDate="2010-05-27" createBy="Rolf">
					<command>
						<sql>
              CREATE TABLE [Customer] (
              [CustomerID] int IDENTITY(1,1),
              [Email] varchar(200) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Customer] PRIMARY KEY ([CustomerID])
              )
              ON [PRIMARY]

              CREATE  UNIQUE  INDEX Customer_Email
              ON Customer ( Email )
            </sql>
					</command>
					<rollback>
						<sql>
              drop table Customer
            </sql>
					</rollback>
				</sqlRunner>
				<sqlRunner index="4" description="Additional tables required" createDate="2010-05-27" createBy="Rolf">
					<command>
						<sql>
              CREATE TABLE [Voucher] (
              [VoucherCode] varchar(20) NOT NULL,
              [TotalItemCount] int NOT NULL,
              [ItemRemaining] int NOT NULL,
              [StartDate] datetime NOT NULL,
              [EndDate] datetime NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Voucher] PRIMARY KEY ([VoucherCode])
              )
              ON [PRIMARY]

            </sql>
					</command>
					<rollback>
						<sql>
              drop table Voucher
            </sql>
					</rollback>
				</sqlRunner>
				<sqlRunner index="5" description="Additional tables required" createDate="2010-05-27" createBy="Rolf">
					<command>
						<sql>
              CREATE TABLE [Order] (
              [GMVTransactionID] int NOT NULL,
              [CustomerID] int NOT NULL,
              [Finalized] bit NOT NULL,
              [TrackCount] int NOT NULL,
              [TotalValue] Decimal(8,2) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Order] PRIMARY KEY ([GMVTransactionID])
              )
              ON [PRIMARY]

              CREATE  INDEX Order_CustomerID ON [Order] ( CustomerID )
            </sql>
					</command>
					<rollback>
						<sql>
              drop table [Order]
            </sql>
					</rollback>
				</sqlRunner>
				<sqlRunner index="6" description="Additional tables required" createDate="2010-05-27" createBy="Rolf">
					<command>
						<sql>
              CREATE TABLE [OrderItem] (
              [GmvTransactionID] int NOT NULL,
              [SellableProductID] bigint NOT NULL,
              [Title] varchar(100) NOT NULL,
              [ArtistName] varchar(100) NOT NULL,
              [Value] Decimal(8,2) NOT NULL,
              [VoucherCode] varchar(20) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__OrderItem] PRIMARY KEY CLUSTERED ([GmvTransactionID],[SellableProductID])
              )
              ON [PRIMARY]

              CREATE  INDEX OrderItem_GmvTransactionID
              ON OrderItem ( GmvTransactionID )
            </sql>
					</command>
					<rollback>
						<sql>
              drop table OrderItem
            </sql>
					</rollback>
				</sqlRunner>
				<sqlRunner index="7" description="Loading table information from csv file" createDate="2010-09-20" createBy="Rolf">
					<command>
						<csv datafile="dbupdate_Data_[Order].csv" table="[Order]"  />
					</command>
					<testData>
						<csv datafile="dbupdate_TestData_[Order].csv" table="[Order]"  />
					</testData>
				</sqlRunner>
			</updates>
		</repository>
	</repositories>
</databaseVersion>

=== rolfwessels/databaseversioncontrol/src/DatabaseVersionControl.Core.Tests/Resources/Sample1.xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseVersion
 defaultProfile="Default"
 xsi:noNamespaceSchemaLocation="DVCSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <profiles>
    <profile id="Default">
      <repositoryProfile
          type="sqlServer"
          connectionString="data source=Localhost;Integrated Security=True;"
          commandTimeout="30"
          databaseName="DvcTest"
          repositoryID="MainDatabase">
        <trackingByTable tableName="DVC_Tracking" autoCreate="True" />
      </repositoryProfile>
  </profile>
  </profiles>
  <repositories>
    <repository id="MainDatabase">
      <initialRunner>
        <sqlRunner index="1" createDate="2010-04-16" description="Initialize script" createBy="Rolf Wessels">
          <command>
            <sql>create database ${dp.DatabaseName}</sql>
          </command>
          <rollback>
            <sql>drop database ${dp.DatabaseName}</sql>
          </rollback>
        </sqlRunner>
      </initialRunner>
      <updates>
        <sqlRunner index="2"  description="Create Product table" createDate="2010-05-25" createBy="Rolf">
          <command>
            <sql>
              CREATE TABLE [Product] (
              [SellableProductID] bigint NOT NULL,
              [Title] varchar(200) NOT NULL,
              [ArtistName] varchar(200) NOT NULL,
              [ImageName] varchar(200) NOT NULL,
              [Price] Decimal(8,2) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Product] PRIMARY KEY ([SellableProductID])
              )
              ON [PRIMARY]
            </sql>
          </command>
          <rollback>
            <sql>drop table Product</sql>
          </rollback>
          <testData>
			  <sql>insert into Product
					(SellableProductID, Title, ArtistName, ImageName, Price, CreateDate, UpdateDate) VALUES
					('4', 'Alpha Beta Gaga - Mark Ronson Remix (Instrumental)', 'Air', '1-0724386120458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
					('14', 'Alpha Beta Gaga (Edit 91)', 'Air', '1-0724386120458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
					('30', 'Le Soleil Est Pr√®s De Moi', 'Air', '1-0724386188458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
					('38', 'Give My Love To Rose', 'Johnny Cash', '114-0829410977685_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
					('62', 'You''re The Nearest Thing To Heaven', 'Johnny Cash', '114-0829410977685_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
					('78', 'Raag Bageshree', 'Hari Prasad Chaurasia', '114-0803680556009_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
					('123', 'Raga Hameer', 'Ravi Shankar', '114-0803680583807_L_F_W.jpg', '123.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
					('142', 'Raga Hameer', 'Ravi Shankar', '114-0803680583807_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31')
				</sql>
          </testData>
        </sqlRunner>
        <sqlRunner index="3"   description="Additional Customer table required" createDate="2010-05-27" createBy="Rolf">
          <command>
            <sql>
              CREATE TABLE [Customer] (
              [CustomerID] int IDENTITY(1,1),
              [Email] varchar(200) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Customer] PRIMARY KEY ([CustomerID])
              )
              ON [PRIMARY]

              CREATE  UNIQUE  INDEX Customer_Email
              ON Customer ( Email )
            </sql>
          </command>
          <rollback>
            <sql>
              drop table Customer
            </sql>
          </rollback>
        </sqlRunner>
        <sqlRunner index="4"   description="Additional Voucher table required" createDate="2010-05-27" createBy="Rolf">
          <command>
            <sql>
              CREATE TABLE [Voucher] (
              [VoucherCode] varchar(20) NOT NULL,
              [TotalItemCount] int NOT NULL,
              [ItemRemaining] int NOT NULL,
              [StartDate] datetime NOT NULL,
              [EndDate] datetime NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Voucher] PRIMARY KEY ([VoucherCode])
              )
              ON [PRIMARY]

            </sql>
          </command>
          <rollback>
            <sql>
              drop table Voucher
            </sql>
          </rollback>
        </sqlRunner>
        <sqlRunner index="5"   description="Additional Order table required" createDate="2010-05-27" createBy="Rolf">
          <command>
            <sql>
              CREATE TABLE [Order] (
              [GMVTransactionID] int NOT NULL,
              [CustomerID] int NOT NULL,
              [Finalized] bit NOT NULL,
              [TrackCount] int NOT NULL,
              [TotalValue] Decimal(8,2) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Order] PRIMARY KEY ([GMVTransactionID])
              )
              ON [PRIMARY]
            </sql>
          </command>
          <rollback>
            <sql>
               drop table [Order]
            </sql>
          </rollback>
        </sqlRunner>
        <sqlRunner index="6" description="Additional Order table required" createDate="2010-05-27" createBy="Rolf">
          <command>
            <sql>
              CREATE  INDEX Order_CustomerID
              ON Order ( CustomerID )
            </sql>
          </command>
        </sqlRunner>
        <sqlRunner index="7"   description="Additional OrderItem required" createDate="2010-05-27" createBy="Rolf">
          <command>
            <sql>
               CREATE TABLE [OrderItem] (
              [GmvTransactionID] int NOT NULL,
              [SellableProductID] bigint NOT NULL,
              [Title] varchar(100) NOT NULL,
              [ArtistName] varchar(100) NOT NULL,
              [Value] Decimal(8,2) NOT NULL,
              [VoucherCode] varchar(20) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__OrderItem] PRIMARY KEY CLUSTERED ([GmvTransactionID],[SellableProductID])
              )
              ON [PRIMARY]
            </sql>
          </command>
          <rollback>
            <sql>
              drop table OrderItem
            </sql>
          </rollback>
        </sqlRunner>
        <sqlRunner index="8"   description="Create index" createDate="2010-05-27" createBy="Rolf">
          <command>
            <sql>
              CREATE  INDEX OrderItem_GmvTransactionID  ON OrderItem ( GmvTransactionID )
            </sql>
          </command>
        </sqlRunner>
      </updates>
    </repository>
  </repositories>
</databaseVersion>

=== rolfwessels/databaseversioncontrol/src/DatabaseVersionControl.Core.Tests/Resources/Sample3.xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseVersion
 defaultProfile="Default"
 xsi:noNamespaceSchemaLocation="..\..\DVCSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <profiles>
      <profile id="Default">
        <repositoryProfile
            type="sqlServer"
            connectionString="data source=Localhost;Integrated Security=True;"
            
            databaseName="DvcTest"
            repositoryID="MainDatabase">
          <trackingByTable tableName="DVC_Tracking" autoCreate="True" />
        </repositoryProfile>
    </profile>
    <profile id="loader">
      <repositoryProfile
          type="sqlServer"
          connectionString="data source=Localhost;Integrated Security=True;"
          commandTimeout="300"
          databaseName="DvcTest"
          repositoryID="MainDatabase">
        <trackingByTable tableName="DVC_Tracking" autoCreate="True" />
        <properties>
          <property name="defaultProp3" >
            defaultProp1Value3OverRide
          </property>
          <property name="defaultProp4" value="defaultProp1Value4" />
          <property name="defaultProp4" value="defaultProp1Value4Duplicate" />
        </properties>
      </repositoryProfile>
    </profile>
  </profiles>
  <repositories>
    <repository id="MainDatabase">
		<properties>
				<property name="defaultProp1" value="defaultProp1Value1" />
				<property name="defaultProp2" value="defaultProp1Value2" />
				<property name="defaultProp3" value="defaultProp1Value3" />
        <property name="defaultProp3" value="defaultProp1Value3Duplicate" />
	</properties>
      <initialRunner>
        <sqlRunner index="1" createDate="2010-04-16" description="Initialize script ${defaultProp3}" createBy="Rolf Wessels">
          <command>
            <sql>create database ${dp.DatabaseName}</sql>
          </command>
          <rollback>
            <sql>drop database ${dp.DatabaseName}</sql>
          </rollback>
        </sqlRunner>
      </initialRunner>
      <updates>
        <sqlRunner index="2"  description="Create Product table" createDate="2010-05-25" createBy="Rolf">
          <command>
            <sql>
              CREATE TABLE [Product]${defaultProp4} (
              [SellableProductID] bigint NOT NULL,
              [Title] varchar(200) NOT NULL,
              [ArtistName] varchar(200) NOT NULL,
              [ImageName] varchar(200) NOT NULL,
              [Price] Decimal(8,2) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Product] PRIMARY KEY ([SellableProductID])
              )
              ON [PRIMARY]
            </sql>
          </command>
          <rollback>
            <sql>drop table Product</sql>
          </rollback>
          <testData>
            <csv datafile="dbupdate_TestData_[Order].csv" table="[Order]"/>
          </testData>
        </sqlRunner>
        
      </updates>
    </repository>
  </repositories>
</databaseVersion>
