=== rolfwessels/databaseversioncontrol/src/DVCSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by rolf_wessels (Private) -->
<!--W3C Schema generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="AT_ProfileTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="sqlServer"/>
      <xs:enumeration value="mySql"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AT_Date">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="AT_String">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="At_Bool">
		<xs:restriction base="xs:string">
			<xs:enumeration value="True"/>
			<xs:enumeration value="False"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AT_int">
		<xs:restriction base="xs:int"/>
	</xs:simpleType>
	<xs:simpleType name="AT_decimal">
		<xs:restriction base="xs:decimal"/>
	</xs:simpleType>
	<xs:element name="property">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="AT_String"/>
					<xs:attribute name="name" type="AT_String" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="properties">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="property" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="updates">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sqlRunner" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="trackingByTable">
		<xs:complexType>
			<xs:attribute name="tableName" type="AT_String" use="required"/>
			<xs:attribute name="autoCreate" type="At_Bool" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="sqlRunner">
		<xs:complexType id="sqlrunnerid">
			<xs:sequence>
				<xs:element ref="command"/>
				<xs:element ref="rollback" minOccurs="0"/>
				<xs:element ref="testData" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="index" type="AT_decimal" use="required"/>
			<xs:attribute name="description" type="AT_String" use="required"/>
			<xs:attribute name="createBy" type="AT_String" use="required"/>
			<xs:attribute name="createDate" type="AT_Date" use="required"/>
      <xs:attribute name="skipTransaction" type="At_Bool" use="optional"/>
      
    </xs:complexType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="file"/>
					<xs:attribute name="files"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="rollback">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sql"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="testData">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="sql"/>
				<xs:element ref="csv"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="repositoryProfile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="trackingByTable"/>
				<xs:element ref="properties" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="type" type="AT_ProfileTypeEnum" use="required"/>
			<xs:attribute name="repositoryID" type="AT_String" use="required"/>
			<xs:attribute name="databaseName" type="AT_String" use="required"/>
			<xs:attribute name="commandTimeout" type="AT_int" use="optional"/>
			<xs:attribute name="connectionString" type="AT_String" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="repository">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="properties" minOccurs="0"/>
				<xs:element ref="initialRunner"/>
				<xs:element ref="updates"/>
			</xs:sequence>
			<xs:attribute name="id" type="AT_String" use="required"/>
		</xs:complexType>
		<xs:unique name="Unique">
			<xs:selector xpath="updates/sqlRunner"/>
			<xs:field xpath="@index"/>
		</xs:unique>
	</xs:element>
	<xs:element name="repositories">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="repository"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="profiles">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="profile"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="profile">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="repositoryProfile"/>
			</xs:sequence>
			<xs:attribute name="id" type="AT_String" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="initialRunner">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="sqlRunner"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="databaseVersion">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="profiles"/>
				<xs:element ref="repositories"/>
			</xs:sequence>
			<xs:attribute name="defaultProfile" type="AT_String" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="command">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="sql"/>
				<xs:element ref="csv"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="csv">
		<xs:complexType>
			<xs:attribute name="datafile" use="required"/>
			<xs:attribute name="table" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rolfwessels/databaseversioncontrol/src/DatabaseVersionControl.Core.Tests/Resources/Sample9.xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseVersion
 defaultProfile="Default"
 xsi:noNamespaceSchemaLocation="..\..\DVCSchema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <profiles>
      <profile id="Default">
        <repositoryProfile
            type="mySql"
            connectionString="data source=Localhost;Integrated Security=True;"
            
            databaseName="DvcTest"
            repositoryID="MainDatabase">
          <trackingByTable tableName="DVC_Tracking" autoCreate="True" />
        </repositoryProfile>
    </profile>
    <profile id="loader">
      <repositoryProfile
          type="sqlServer"
          connectionString="data source=Localhost;Integrated Security=True;"
          commandTimeout="300"
          databaseName="DvcTest"
          repositoryID="SecondaryDatabase">
        <trackingByTable tableName="DVC_Tracking" autoCreate="True" />
        <properties>
          <property name="defaultProp3" >
            defaultProp1Value3OverRide
          </property>
          <property name="defaultProp4" value="defaultProp1Value4" />
          <property name="defaultProp4" value="defaultProp1Value4Duplicate" />
        </properties>
      </repositoryProfile>
    </profile>
  </profiles>
  <repositories>
    <repository id="MainDatabase">
		<properties>
				<property name="defaultProp1" value="defaultProp1Value1" />
				<property name="defaultProp2" value="defaultProp1Value2" />
				<property name="defaultProp3" value="defaultProp1Value3" />
        <property name="defaultProp3" value="defaultProp1Value3Duplicate" />
	   </properties>
      <initialRunner>
        <sqlRunner index="1" createDate="2010-04-16" description="Initialize script ${defaultProp3}" createBy="Rolf Wessels">
          <command>
            <sql>create database ${dp.DatabaseName}</sql>
          </command>
          <rollback>
            <sql>drop database ${dp.DatabaseName}</sql>
          </rollback>
        </sqlRunner>
      </initialRunner>
      <updates>
        <sqlRunner index="2"  description="Create Product table" createDate="2010-05-25" createBy="Rolf">
          <command>
            <sql>
              CREATE TABLE [Product]${defaultProp4} (
              [SellableProductID] bigint NOT NULL,
              [Title] varchar(200) NOT NULL,
              [ArtistName] varchar(200) NOT NULL,
              [ImageName] varchar(200) NOT NULL,
              [Price] Decimal(8,2) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Product] PRIMARY KEY ([SellableProductID])
              )
              ON [PRIMARY]
            </sql>
          </command>
          <rollback>
            <sql>drop table Product</sql>
          </rollback>
          <testData>
			  <sql>
          insert into Product${defaultProp3}
          (SellableProductID, Title, ArtistName, ImageName, Price, CreateDate, UpdateDate) VALUES
          ('4', 'Alpha Beta Gaga - Mark Ronson Remix (Instrumental)', 'Air', '1-0724386120458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
          ('14', 'Alpha Beta Gaga (Edit 91)', 'Air', '1-0724386120458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
          ('30', 'Le Soleil Est Près De Moi', 'Air', '1-0724386188458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
          ('38', 'Give My Love To Rose', 'Johnny Cash', '114-0829410977685_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
          ('62', 'You''re The Nearest Thing To Heaven', 'Johnny Cash', '114-0829410977685_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
          ('78', 'Raag Bageshree', 'Hari Prasad Chaurasia', '114-0803680556009_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
          ('123', 'Raga Hameer', 'Ravi Shankar', '114-0803680583807_L_F_W.jpg', '123.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
          ('142', 'Raga Hameer', 'Ravi Shankar', '114-0803680583807_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31')
        </sql>
          </testData>
        </sqlRunner>
        <sqlRunner index="3"  description="Create Product table" createDate="2010-05-25" createBy="Rolf" skipTransaction="True">
          <command>
            <sql>
              CREATE TABLE [Product]${defaultProp4} (
              [SellableProductID] bigint NOT NULL,
              [Title] varchar(200) NOT NULL,
              [ArtistName] varchar(200) NOT NULL,
              [ImageName] varchar(200) NOT NULL,
              [Price] Decimal(8,2) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Product] PRIMARY KEY ([SellableProductID])
              )
              ON [PRIMARY]
            </sql>
          </command>
          <rollback>
            <sql>drop table Product</sql>
          </rollback>
          <testData>
            <sql>
              insert into Product${defaultProp3}
              (SellableProductID, Title, ArtistName, ImageName, Price, CreateDate, UpdateDate) VALUES
              ('4', 'Alpha Beta Gaga - Mark Ronson Remix (Instrumental)', 'Air', '1-0724386120458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('14', 'Alpha Beta Gaga (Edit 91)', 'Air', '1-0724386120458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('30', 'Le Soleil Est Près De Moi', 'Air', '1-0724386188458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('38', 'Give My Love To Rose', 'Johnny Cash', '114-0829410977685_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('62', 'You''re The Nearest Thing To Heaven', 'Johnny Cash', '114-0829410977685_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('78', 'Raag Bageshree', 'Hari Prasad Chaurasia', '114-0803680556009_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('123', 'Raga Hameer', 'Ravi Shankar', '114-0803680583807_L_F_W.jpg', '123.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('142', 'Raga Hameer', 'Ravi Shankar', '114-0803680583807_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31')
            </sql>
          </testData>
        </sqlRunner>
      </updates>
    </repository>

    <repository id="MainDatabase">
      <properties>
        <property name="defaultProp1" value="defaultProp1Value1" />
        <property name="defaultProp2" value="defaultProp1Value2" />
        <property name="defaultProp3" value="defaultProp1Value3" />
        <property name="defaultProp3" value="defaultProp1Value3Duplicate" />
      </properties>
      <initialRunner>
        <sqlRunner index="1" createDate="2010-04-16" description="Initialize script ${defaultProp3}" createBy="Rolf Wessels">
          <command>
            <sql>create database ${dp.DatabaseName}</sql>
          </command>
          <rollback>
            <sql>drop database ${dp.DatabaseName}</sql>
          </rollback>
        </sqlRunner>
      </initialRunner>
      <updates>
        <sqlRunner index="2"  description="Create Product table" createDate="2010-05-25" createBy="Rolf">
          <command>
            <sql>
              CREATE TABLE [Product]${defaultProp4} (
              [SellableProductID] bigint NOT NULL,
              [Title] varchar(200) NOT NULL,
              [ArtistName] varchar(200) NOT NULL,
              [ImageName] varchar(200) NOT NULL,
              [Price] Decimal(8,2) NOT NULL,
              [CreateDate] datetime NOT NULL,
              [UpdateDate] datetime NOT NULL
              CONSTRAINT [PK__Product] PRIMARY KEY ([SellableProductID])
              )
              ON [PRIMARY]
            </sql>
          </command>
          <rollback>
            <sql>drop table Product</sql>
          </rollback>
          <testData>
            <sql>
              insert into Product${defaultProp3}
              (SellableProductID, Title, ArtistName, ImageName, Price, CreateDate, UpdateDate) VALUES
              ('4', 'Alpha Beta Gaga - Mark Ronson Remix (Instrumental)', 'Air', '1-0724386120458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('14', 'Alpha Beta Gaga (Edit 91)', 'Air', '1-0724386120458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('30', 'Le Soleil Est Près De Moi', 'Air', '1-0724386188458_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('38', 'Give My Love To Rose', 'Johnny Cash', '114-0829410977685_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('62', 'You''re The Nearest Thing To Heaven', 'Johnny Cash', '114-0829410977685_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('78', 'Raag Bageshree', 'Hari Prasad Chaurasia', '114-0803680556009_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('123', 'Raga Hameer', 'Ravi Shankar', '114-0803680583807_L_F_W.jpg', '123.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31'),
              ('142', 'Raga Hameer', 'Ravi Shankar', '114-0803680583807_L_F_W.jpg', '1.00', '2010-05-01 14:04:24', '2010-05-01 16:38:31')
            </sql>
          </testData>
        </sqlRunner>
       
      </updates>
    </repository>
  </repositories>
</databaseVersion>
